documents: !QVariantList
  []
editors: !QVariantMap
  elements: !QVariantList
    - !QVariantList
      []
  state: AAAA/wAAAAEAAAABAAAAZAH/////AQAAAAEA
mainWindow:
  detached: !QVariantMap
    documents-dock: ""
    help-dock: ""
    post-dock: ""
  geometry: AdnQywADAAAAAABjAAAAPQAACVMAAAXBAAAAYwAAAGIAAAlTAAAFwQAAAAAAAAAACgAAAABjAAAAYgAACVMAAAXB
  state: AAAA/wAAAAD9AAAAAgAAAAAAAAAAAAAAAPwCAAAAAfsAAAAcAGQAbwBjAHUAbQBlAG4AdABzAC0AZABvAGMAawAAAAAA/////wAAAGEA////AAAAAQAABEYAAAUr/AIAAAAC+wAAABIAaABlAGwAcAAtAGQAbwBjAGsBAAAAGAAAAuQAAABPAP////sAAAASAHAAbwBzAHQALQBkAG8AYwBrAQAAAv0AAAJGAAAATwD///8AAASqAAAFKwAAAAEAAAACAAAAAQAAAAL8AAAAAA==