documents: !QVariantList
  - /home/jms/git/wtkns/research/vfthm/requirements.txt
editors: !QVariantMap
  elements: !QVariantList
    - !QVariantList
      - !QVariantMap
        documentIndex: 0
        position: 0
  state: AAAA/wAAAAEAAAABAAAAZAH/////AQAAAAEA
mainWindow:
  detached: !QVariantMap
    documents-dock: ""
    help-dock: ""
    post-dock: ""
  geometry: AdnQywADAAAAAAFoAAAAGwAACGEAAAWfAAABaAAAAEAAAAhhAAAFnwAAAAAAAAAACgAAAAFoAAAAQAAACGEAAAWf
  state: AAAA/wAAAAD9AAAAAgAAAAAAAADIAAAFK/wCAAAAAfsAAAAcAGQAbwBjAHUAbQBlAG4AdABzAC0AZABvAGMAawAAAAAYAAAFKwAAAGEA////AAAAAQAAAlsAAAUr/AIAAAAC+wAAABIAaABlAGwAcAAtAGQAbwBjAGsAAAAAGAAAAuQAAABPAP////sAAAASAHAAbwBzAHQALQBkAG8AYwBrAQAAABgAAAUrAAAATwD///8AAASeAAAFKwAAAAEAAAACAAAAAQAAAAL8AAAAAA==